name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Remove unused imports and variables with autoflake
        run: |
          autoflake --in-place --remove-unused-variables --remove-all-unused-imports -r .
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Check formatting with black
        run: |
          black --check .
      - name: Check import order with isort
        run: |
          isort --check-only .
      - name: Run tests
        run: |
          pytest
